on: workflow_dispatch

name: Update and release

jobs:
  updateDataAndRelease:
    name: Update data and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Chmod
        run: chmod +x ./script/test.sh
      - name: Update data and release
        run: npm run release2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
